FROM node:20-alpine

WORKDIR /app

# Cache package dependencies
COPY package*.json ./
RUN npm install

# Copy frontend source files
COPY . .

EXPOSE 5500

ENV HOST=0.0.0.0 \
    PORT=5500

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5500"]
