export const CALL_STATES = {
  IDLE: 'IDLE',
  OUTGOING: 'OUTGOING',
  RINGING: 'RINGING',
  INCOMING: 'INCOMING',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  RECONNECTING: 'RECONNECTING',
  ENDED: 'ENDED',
  REJECTED: 'REJECTED',
  BUSY: 'BUSY',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
};

export const CALL_TYPES = {
  VOICE: 'voice',
  VIDEO: 'video',
};
